export const getNarrativeForRoll = (roll: number, max: number = 20): string => {
  if (roll === 1) {
    const criticalFailures = [
      "A catastrophic miscalculation. The world seems to conspire against you.",
      "You stumble at the worst possible moment. Wasted.",
      "One does not simply roll a 1. The Eye of Sauron is judging you.",
      "I've got a bad feeling about this...",
      "Reality is often disappointing.",
      "You had ONE job!",
      "My disappointment is immeasurable, and my day is ruined.",
      "I am never going to financially recover from this.",
      "Emotional damage! The dice have forsaken you.",
      "Did you put your name in the Goblet of Fire, Harry?! ...Dumbledore asked calmly.",
      "Congratulations, you played yourself.",
      "Another happy landing... said no one ever.",
      "You were the Chosen One! You were supposed to destroy the 1s, not join them!",
      "Houston, we have a problem. A really big, critical problem.",
      "An elegant failure for a less civilized age.",
      "Fly, you fools! ...Oh wait, you just fell off the cliff instead.",
      "F in the chat for this tragic attempt.",
      "A natural 1. You question your life choices as everything falls apart.",
      "Your confidence betrays you. An abysmal outcome.",
      "A spectacular failure that will be sung about in taverns as a cautionary tale.",
      "Oof. I think you got a bit of the bad juju there.",
      "You died. (Dark Souls death screen intensifies)",
      "WASTED. Better luck in the next spawn.",
      "It is time to delete this character.",
      "My expectations were low but holy cow.",
      "This roll belongs in a museum... of what not to do.",
      "A series of unfortunate events, concentrated in one single roll.",
      "You've activated my trap card!",
      "I'm not mad, I'm just disappointed.",
      "Roll 1 to pay respects.",
      "D'oh! That did not go as planned.",
      "That was not very cash money of you.",
      "Look at the bright side: it can't possibly get any worse. (Or can it?)",
      "I'm in danger! *giggles nervously*",
      "This is fine. (Everything is on fire in the background)",
      "To the shadow realm you go!",
      "Well, that was a free trial of absolute failure.",
      "You tried to do a barrel roll, but just crashed.",
      "Mission failed, we'll get 'em next time.",
      "Stop! Stop! He's already dead!",
      "It's a bold strategy Cotton, let's see if it pays off for 'em.",
      "I can't believe you've done this.",
      "Why are we still here? Just to suffer?",
      "The RNG gods are laughing at you right now.",
      "You fell victim to one of the classic blunders!",
      "Hello darkness, my old friend...",
      "You rolled a 1. Your ancestors are weeping.",
      "Error 404: Luck not found.",
      "A swing and a massive, embarrassing miss.",
      "This is the darkest timeline.",
      "You are the weakest link. Goodbye.",
      "Moments before disaster.",
      "Even a broken clock is right twice a day, but this roll wasn't.",
      "You rolled a 1. The dungeon master chuckles softly.",
      "Crit fail! Time to write a new character sheet."
    ];
    return criticalFailures[Math.floor(Math.random() * criticalFailures.length)];
  }

  if (roll === max) {
    const criticalSuccesses = [
      "UNLIMITED POWER! Masterful form!",
      "I am inevitable. A flawless, legendary execution.",
      "You strike with godlike precision and devastating force.",
      "The stars align. This is where the fun begins!",
      "Maximum effort! You exceed all expectations.",
      "It's over! You have the high ground now.",
      "Absolutely legendary. They will write sagas about this day.",
      "Flawless victory! Outstanding move.",
      "I have become Death, the destroyer of worlds... or at least this challenge.",
      "You're goddamn right. Perfection incarnate.",
      "The weave of magic bends to your will. A glorious triumph.",
      "Behold! The ultimate manifestation of fate.",
      "A stroke of absolute brilliance! To infinity and beyond!",
      "The impossible becomes reality. A perfect natural roll!",
      "Show me the money! A masterpiece of a roll.",
      "Say hello to my little friend! (It's a maximum roll!)",
      "Outstanding move! Modern problems require outstanding rolls.",
      "Chewie, we're home. Perfection is here.",
      "Is this the real life? Is this just fantasy? Yes, a perfect roll!",
      "They said it could not be done. You proved them wrong.",
      "I'm the king of the world!",
      "Witness me! Shiny and chrome!",
      "Go ahead, make my day. And you just did!",
      "Limitless Power!",
      "Like a boss! Totally crushed it.",
      "Houston, we have liftoff! Excellent peak performance.",
      "That is America's roll.",
      "You have chosen... wisely.",
      "Nothing is impossible! JUST DO IT!",
      "Apex performance. The Gods of RNG are smiling upon you.",
      "That's a lot of damage! (To your foes, that is)",
      "He's too dangerous to be left alive!",
      "A roll fit for a hero of legend.",
      "Are you not entertained?!",
      "Praise the sun! A grossly incandescent roll!",
      "This is Sparta! Absolute dominance.",
      "You merely adopted the dark. I was born in it.",
      "I love it when a plan comes together.",
      "You bow to no one.",
      "We're in the endgame now.",
      "To boldly go where no roll has gone before.",
      "I am the danger.",
      "It's super effective!",
      "Critical Hit! The enemy is staggered.",
      "You have ascended beyond mere mortals.",
      "A critical success. The bards will sing of this moment.",
      "Glory and honor! A triumphant outcome.",
      "You rolled max! RNGesus is with you.",
      "Legendary status unlocked.",
      "You rolled the maximum! What sorcery is this?",
      "Fatality! Flawless victory."
    ];
    return criticalSuccesses[Math.floor(Math.random() * criticalSuccesses.length)];
  }

  const percentage = roll / max;

  if (percentage <= 0.3) {
    const lows = [
      "I am asking you once again to roll better.",
      "So you're saying there's a chance? ...Nope, that's still pretty bad.",
      "Not great, not terrible... Actually, no, it's pretty terrible.",
      "Look how they massacred my boy.",
      "This is not the roll you are looking for.",
      "You tried so hard, and got so far. But in the end, it doesn't even matter.",
      "Task failed successfully. Better luck next time.",
      "That's rough, buddy.",
      "Please insert 25 cents to try again.",
      "Are you not entertained? No, because that was a terrible attempt.",
      "It is honest work, but barely.",
      "A weak showing. The outcome is less than favorable.",
      "You hesitate, and the opportunity slips away.",
      "Clumsy and awkward. The universe sighs.",
      "Oof, size: LARGE.",
      "Press F to pay respects to this roll.",
      "We don't make mistakes, just happy accidents. Let's call this a very happy accident.",
      "Are ya winning, son? ...Clearly not with that roll.",
      "You can't handle the truth! (The truth is this roll is pretty weak).",
      "My precious! ...Wait, no, don't look at it, it's terrible.",
      "Is this some kind of peasant joke I'm too lucky to understand?",
      "Aw, did someone get addicted to low rolls?",
      "Houston, we've had a minor setback.",
      "You tried. Star sticker for effort! ⭐",
      "Not quite the chosen one, are you?",
      "Reality check: You need to blow on the dice next time.",
      "This ain't it, chief.",
      "You missed the mark by a mile.",
      "Even a Stormtrooper could aim better.",
      "Slightly better than a 1, which isn't saying much.",
      "A disappointing display of skill.",
      "The universe gave you a pity point.",
      "You trip over your own feet.",
      "I've seen mudcrabs with better reflexes.",
      "Let's just pretend that didn't happen.",
      "You gaze into the abyss, and the abyss laughs.",
      "A tragedy in one act.",
      "The universe has politely declined your request.",
      "Critical yikes.",
      "Did you even try, or was that an accident?",
      "I expected nothing and I'm still let down.",
      "That roll was so bad it needs a redemption arc.",
      "I'm not mad, just disappointed.",
      "Skill issue detected.",
      "Your dice clearly have it in for you.",
      "Even the NPCs are laughing."
    ];
    return lows[Math.floor(Math.random() * lows.length)];
  }

  if (percentage <= 0.7) {
    const mediums = [
      "Perfectly balanced, as all things should be.",
      "Not great, not terrible. Exactly 3.6 Roentgen of luck.",
      "It's a simple spell, but quite unbreakable.",
      "May the rolls be ever in your favor.",
      "This is the way. Standard, reliable, average.",
      "A wizard is never late, nor is he early. He rolls precisely what he means to.",
      "You shall not pass! ...Well, actually, you might pass, it's a decent attempt.",
      "Elementary, my dear Watson. Quite standard.",
      "I can do this all day. (Proceeds to roll perfectly average numbers).",
      "An average effort. It might just be enough.",
      "You do what is necessary, nothing more.",
      "A standard execution yielding standard results.",
      "Acceptable, though entirely unimpressive.",
      "You hold your ground, but gain no clear advantage.",
      "Honest work. It ain't much, but it's honest.",
      "Just keep swimming, just keep swimming.",
      "It is acceptable. Not mind-blowing, but it gets the job done.",
      "You are on this council, but we do not grant you the rank of Master.",
      "Help me, Obi-Wan Kenobi, you're my only hope... for an average result.",
      "Keep your secrets then. Just a standard average roll.",
      "Not a triumph, but certainly not a disaster.",
      "A perfectly mundane outcome. The crowd is politely quiet.",
      "Balanced on the edge of greatness and failure.",
      "You survived. No more, no less.",
      "Middle of the pack. Just an ordinary day.",
      "It passes the vibe check, barely.",
      "Adequate. You meet expectations.",
      "Nothing to write home about.",
      "You did the thing. Congratulations.",
      "A completely whelming experience.",
      "50% of the time, it works every time.",
      "Meh.",
      "You perform with the enthusiasm of a DMV employee.",
      "A beige roll for a beige moment.",
      "The dice shrug their shoulders.",
      "You are technically correct. The best kind of correct.",
      "You rolled a solid C+.",
      "Not the hero we deserve, nor the one we need right now.",
      "Another day, another remarkably average roll."
    ];
    return mediums[Math.floor(Math.random() * mediums.length)];
  }

  const highs = [
    "I am Iron Man. A highly effective effort.",
    "Is it possible to learn this power?",
    "Look at me. I'm the captain now.",
    "He's beginning to believe! Excellent execution.",
    "Great kid, don't get cocky!",
    "You're breathtaking!",
    "They're taking the Hobbits to Isengard!",
    "That still only counts as one! A powerful attempt.",
    "I am the one who knocks! Striking with great confidence.",
    "You're a wizard, Harry. Admirably precise.",
    "There is no spoon. You bend reality in your favor.",
    "A solid, skilled maneuver. You strike true.",
    "You execute your plan with admirable precision.",
    "A powerful attempt that connects solidly.",
    "You push past the obstacles with striking confidence.",
    "Excellent! Bill & Ted would be proud.",
    "I feel the need... the need for speed! And high rolls!",
    "With great power comes great rolls.",
    "I see this as an absolute win!",
    "Very nice, how much? High quality roll.",
    "A surprise, to be sure, but a welcome one.",
    "May the Force be with you. It clearly is.",
    "So civilized. A masterful showing.",
    "A near-perfect strike. The enemies are sweating.",
    "Impressive. Most impressive.",
    "You're in the endgame now.",
    "This is where the fun begins.",
    "We will watch your career with great interest.",
    "A fantastic display of prowess.",
    "Almost perfect! Just a hair away.",
    "You feel the power coursing through you.",
    "A mighty blow that leaves a mark.",
    "The dice favor the bold.",
    "You strike with the fury of a thousand suns (almost).",
    "A glorious maneuver. Huzzah!",
    "Top tier performance, well played.",
    "A roll worthy of a seasoned adventurer.",
    "The bards will take notes on this one.",
    "Unstoppable! You are a force of nature.",
    "A roll crafted by the gods themselves.",
    "Exquisite technique, flawlessly executed.",
    "You shattered their expectations and their armor."
  ];
  return highs[Math.floor(Math.random() * highs.length)];
};
